django2/mysecond/polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns = [
    path('', views.list, name='list'),      # http://localhost:8000/polls/index.html
    path('test/', views.test),  # http://localhost:8000/polls/test/
    path('insert/', views.insert, name='insert'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote/', views.vote, name='vote')


#    path('insert/', views.insert),  # http://localhost:8000/polls/insert/index.html
]

django2/mysecond/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=100)  # 좋아하는 색은?
    pub_date = models.DateTimeField('date published')
    # table의 이름을 변경
    class Meta:
        db_table='question'
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=100)
    vote = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

django2/mysecond/polls/views.py
from django.shortcuts import render
from .models import Question
from django.shortcuts import get_object_or_404

# Create your views here. (java = controller)
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    selected_choice = question.choice_set.get(id=request.POST['ch'])
    selected_choice.vote += 1
    selected_choice.save()
    return render(request, 'polls/vote.html', {'q':question})


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request,'polls/detail.html', {'q':question})


def test(request):
    # 삽입 : save()
    # q = Question(question_text='좋아하는 색은', pub_date='2020-01-27')
    # q.save()  #  저장
    #
    # q = Question(question_text='좋아하는 음식은', pub_date='2020-01-27')
    # q.save()
    #
    # q = Question(question_text='좋아하는 만화는', pub_date='2020-01-27')
    # q.save()
    #
    # q = Question(question_text='좋아하는 색깔은', pub_date='2020-01-27')
    # q.save()

    # 수정 : save(), id = ''가 입력이 되면 수정이 된다.
    # q = Question(id=5, question_text='좋아하는 만화는', pub_date='2020-01-28')
    # q.save()

    # 조회
    # qlist = Question.objects.all()
    # qlist = Question.objects.all().order_by('-id')  # -는 역순으로 정렬
    # print(type(qlist))
    # for q in qlist:
    #     print(q.question_text, q.pub_date)

    # 삭제
    # q = Question.objects.get(id=2)
    # q.delete()

    return render(request, 'polls/test.html')


def insert(request):
    q = Question(question_text='가고 싶은 곳은?', pub_date='2020-01-28')
    q.save()
    return render(request, 'polls/insert.html')


def list(request):
    qlist = Question.objects.all()
    temp = {'qs' : qlist}
    return render(request, 'polls/list.html', temp)

django2/mysecond/polls/templates/polls/detail.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<h2>polls/detail</h2>
<table class="table">
    <tr>
        <td>질문 내용 : </td>
        <td>{{q.question_text}}</td>
    </tr>
    <tr>
        <td>질문 날짜 : </td>
        <td>{{q.pub_date}}</td>
    </tr>
</table>
<form class="table" method="post" action="{% url 'polls:vote' q.id %}">
    {%csrf_token%}
    <div>답변 내용 : </div>
    {% for c in q.choice_set.all %}
    <div>
        <input type="radio" name="ch" value="{{c.id}}"/>{{c}}
    </div>
    {% endfor %}
    <br>
    <input type="submit" value="투표하기" class="btn btn-success">
    <span style="float:right;"><a href="/polls" class="btn btn-success" role="button">설문목록</a></span>
</form>
{% endblock %}

django2/mysecond/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
index.html
</body>
</html>

django2/mysecond/polls/templates/polls/insert.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<h2>질문내용 입력</h2>
<div class="container">
    <form>
        <div class="form-group">
            <label for="usr">질문내용 : </label>
            <input type="text" class="form-control" id="question_text" name="question_text">
        </div>
        <div class="form-group">
            <label for="usr">질문내용 : </label>
            <input type="text" class="form-control" id="pub_date" name="pub_date">
        </div>
    </form>
</div>
{% endblock %}

django2/mysecond/polls/templates/polls/list.html
{% extends 'base.html' %}
{% block title %}설문관리{% endblock %}

{% block content %}
<h3>polls/list.html</h3>
<ul class="container">
{% for q in qs %}
    <li class="list-group-item"><a href="{% url 'polls:detail' q.id %}">{{q.id}}  --  {{q.question_text}}  --  {{q.pub_date}}</a></li>
{% endfor %}
</ul>
{% endblock %}

django2/mysecond/polls/templates/polls/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
테스트 입니다~
</body>
</html>

django2/mysecond/polls/templates/polls/vote.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<h2>polls/vote</h2>
<table class="table">
    <tr>
        <td>질문 내용 : </td>
        <td>{{q.question_text}}</td>
    </tr>
    <tr>
        <td>질문 날짜 : </td>
        <td>{{q.pub_date}}</td>
    </tr>
</table>
<table class="table">
    <tr>
        <td align="center">답변 결과</td>
        <td>투표수</td>
    </tr>
    {% for c in q.choice_set.all %}
    <tr>
        <td align="center">{{c.choice_text}}</td>
        <td>{{c.vote}}</td>
    </tr>
    {% endfor %}
</table>
<a href="{%url 'polls:detail' q.id%}" class="btn btn-success" role="button">돌아가기</a>
<span style="float:right;"><a href="{%url 'polls:list'%}" class="btn btn-success" role="button" >목록가기</a></span>
{% endblock %}