django3/shoppingmall/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BookTemplate.as_view(), name='index'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
    path('publisher/insert/', views.PublisherCreate.as_view(), name='publisher_insert'),
    path('publisher/update/<int:pk>', views.PublisherUpdate.as_view(), name='publishser_update'),
    path('publisher/delete/<int:pk>', views.PublisherDelete.as_view(), name='publishser_delete'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('author/insert/', views.AuthorCreate.as_view(), name='author_insert'),
    path('author/update/<int:pk>/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/delete/<int:pk>/', views.AuthorDelete.as_view(), name='author_delete'),

]
# path('', views.클래스명.as_view(), name='')
# 진입메소드 : as_view(), urls.py

django3/shoppingmall/books/templates/books/author_delete.html
{% extends 'base.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/author_delete</h2>
<p/>
{{object.name}}
<p/>
<p>정말 삭제 하시겠습니까?</p>
<form method="post">
    {%csrf_token%}
    <input type="submit" value="삭제" class="btn btn-danger"/>
</form>
{% endblock %}

django3/shoppingmall/books/templates/books/author_detail.html
{% extends 'base_books.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/author_detail</h2>
<table class="table">
    <tr>
        <td>사  진 : {{object.photo.url}}</td>
        <td><img src="{{object.photo.url}}"/></td>
    </tr>
    <tr>
        <td>이  름 : </td>
        <td>{{object.name}}</td>
    </tr>
    <tr>
        <td>소  개 : </td>
        <td>{{object.intro}}</td>
    </tr>
    <tr>
        <td>이메일 : </td>
        <td>{{object.email}}</td>
    </tr>
    <tr>
        <td colspan="2">
            <a href="/books/author/update/{{object.id}}" class="btn btn-success">수정</a>
            <a href="/books/author/delete/{{object.id}}" class="btn btn-danger">삭제</a>
            <a href="/books/author" class="btn btn-success" style="float:right;">목록가기</a>
        </td>
    </tr>
</table>
{% endblock %}

django3/shoppingmall/books/templates/books/author_insert.html
{% extends 'base.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>author/insert</h2>
<form method="post">
    {%csrf_token%}
    <table class="table">
        {{form.as_table}}
        <tr>
            <td colspan="2"><input type="submit" value="등록" class="btn btn-success"/></td>
        </tr>
    </table>
</form>
{% endblock %}

django3/shoppingmall/books/templates/books/author_list.html
{% extends 'base_books.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/author_list</h2>
<p/>
<ol>
    {% for a in object_list %}
    <li><a href="{%url 'books:author_detail' a.id%}">{{a.name}}</a></li>
    {% endfor %}
</ol>
<a href="/books/author/insert" class="btn btn-success">등록</a>
{% endblock %}

django3/shoppingmall/books/templates/books/author_update.html
{% extends 'base.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>author/update</h2>
<p/>
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="수정" class="btn btn-success"/>
</form>
{% endblock %}

django3/shoppingmall/books/templates/books/book_detail.html
{% extends 'base.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/book_detail</h2>
<table class="table">
    <tr>
        <td>책제목 : </td>
        <td>{{object.title}}</td>
    </tr>
    <tr>
        <td>출판사 : </td>
        <td>{{object.publisher}}</td>
    </tr>
    <tr>
        <td>출판일 : </td>
        <td>{{object.pub_date}}</td>
    </tr>
    <tr>
        <td>지은이 : </td>
        <td>{%for a in object.authors.all%}{{a}}&nbsp;&nbsp;&nbsp;{%endfor%}</td>
    </tr>
    <tr>
        <td colspan="2">
            <a href="/books/book" class="btn btn-success">목록가기</a>
        </td>
    </tr>
</table>
{% endblock %}

django3/shoppingmall/books/templates/books/book_list.html
{% extends 'base.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/book_list</h2>
<ol>
    {% for b in object_list %}
    <li><a href="{%url 'books:book_detail' b.id%}">{{b.title}}</a></li>
    {% endfor %}
</ol>
<a href="/books/book/insert" class="btn btn-success">등록</a>
{% endblock %}

django3/shoppingmall/books/templates/books/index.html
{%extends 'base_books.html'%}}
{%block content%}
<h2>books/index</h2>
<p/>
<ol>
{%for k in kind%}
    {%with 'books:'|add:k|add:'_list' as url1%}
    <li><a href="{%url url1%}">{{k}}</a> - {{url1}}</li>
    {%endwith%}
{%endfor%}
</ol>
{%endblock%}

django3/shoppingmall/books/templates/books/publisher_delete.html
{% extends 'base_books.html' %}
{% block title %}Publisher{% endblock %}

{% block content %}
<h2>books/publisher_delete</h2>
<p/>
{{object.name}}
<p/>
<p>정말 삭제 하시겠습니까?</p>
<form method="post">
    {%csrf_token%}
    <input type="submit" value="삭제" class="btn btn-danger"/>
</form>
{% endblock %}

django3/shoppingmall/books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/publisher_detail</h2>
<table class="table">
    <tr>
        <td>출판사 : </td>
        <td>{{object.name}}</td>
    </tr>
    <tr>
        <td>주  소 : </td>
        <td>{{object.address}}</td>
    </tr>
    <tr>
        <td>사이트 : </td>
        <td>{{object.website}}</td>
    </tr>
    <tr>
        <td colspan="2">
            <a href="/books/publisher/update/{{object.id}}" class="btn btn-success">수정</a>
            <a href="/books/publisher/delete/{{object.id}}" class="btn btn-danger">삭제</a>
            <a href="/books/publisher" class="btn btn-success" style="float:right;">목록가기</a>
        </td>
    </tr>
</table>
{% endblock %}

django3/shoppingmall/books/templates/books/publisher_list.html
{% extends 'base_books.html' %}
{% block title %}Author{% endblock %}

{% block content %}
<h2>books/publisher_list</h2>
<ol>
    {% for p in object_list %}
    <li><a href="{%url 'books:publisher_detail' p.id%}">{{p.name}}</a></li>
    {% endfor %}
</ol>
<a href="/books/publisher/insert" class="btn btn-success">등록</a>
{% endblock %}

django3/shoppingmall/books/templates/books/publisher_update.html
{% extends 'base_books.html' %}
{% block title %}Publisher{% endblock %}

{% block content %}
<h2>books/author_update</h2>
<p/>
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="수정" class="btn btn-success"/>
</form>
{% endblock %}

django3/shoppingmall/books/templates/books/publishser_insert.html
{% extends 'base_books.html' %}
{% block title %}Publisher{% endblock %}

{% block content %}
<h2>books/publisher_insert</h2>
<form method="post" enctype="multipart/form-data">
    {%csrf_token%}
    <table class="table">
        {{form.as_table}}
        <tr>
            <td colspan="2">
                <input type="submit" value="등록" class="btn btn-success"/>
            </td>
        </tr>
    </table>
</form>
{% endblock %}