django2/mysecond/member/urls.py
from django.urls import path, include
from . import views
app_name = 'member'
urlpatterns = [
    # path('url패턴', 수행할 함수 또는 클래스, name = 이름),
    path('', views.index, name='index'), # http://localhost:8000/member:insert
    path('insert/', views.insert, name='insert2'),
    path('list/', views.list, name='list2'),
    path('<int:member_id>/', views.detail, name='detail'),
    path('<int:member_id>/delete/', views.delete, name='delete'),
    path('<int:member_id>/update/', views.update, name='update'),
]

django2/mysecond/member/models.py
from django.db import models

# Create your models here.
class Member(models.Model):
    username = models.CharField(max_length=50)
    pw = models.CharField(max_length=50)
    hp = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    name = models.CharField(max_length=50)
    regdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.username+' - '+self.name

django2/mysecond/member/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Member
from django.contrib.auth.hashers import make_password
from django.shortcuts import get_object_or_404
from django.urls import reverse
from datetime import datetime


def update(request, member_id):
    if request.method == 'GET':
        member = get_object_or_404(Member, pk=member_id)
        # member.save()
        return render(request, 'member/update.html',{'m':member})
    elif request.method == 'POST':
        id = request.POST['id']
        username = request.POST['username']
        hp = request.POST['hp']
        email = request.POST['email']
        name = request.POST['name']
        pw = request.POST['pw']
        regdate = datetime.now()
        m = Member(
            id=id,
            username=username,
            hp=hp,
            email=email,
            name=name,
            pw=pw,
            regdate=regdate
        )
        m.save()
        return HttpResponseRedirect(reverse('member:detail', args=(member_id,)))



def detail(request, member_id):
    # member = Member.objects.get(id=member_id)
    member = get_object_or_404(Member, pk=member_id)
    return render(request, 'member/detail.html', {'m': member})


def delete(request, member_id):
    member = get_object_or_404(Member, pk=member_id)
    member.delete()
    return HttpResponseRedirect(reverse('member:list2'))

def list(request):
    members = Member.objects.all()
    return render(request, 'member/list.html', {'ms': members})

# Create your views here.
def index(request):
    fruit = {'names': ['애플망고', '사각수박', '멜론'],
             'colors': ['red', 'blue', 'white', 'green'],
             'number': [1, 2, 3, 4, 5]}
    return render(request, 'member/index.html', fruit)

# render(request, 템플릿명[사전형객체]
# 템플릿변수 {{변수}}
# 템플릿태그 {% 태그 %}
# 템플릿필터 |
def insert(request):
    if request.method == 'GET':
        return render(request, 'member/insert.html')
    elif request.method == 'POST':
        # DB에 넣어라
        username = request.POST['username']
        pw = request.POST['pw']
        repw = request.POST['repw']
        hp = request.POST['hp']
        email = request.POST['email']
        name = request.POST['name']
        msg = {}  # return은 딕셔너리로
        if pw != repw:
            msg['err'] = "비밀번호를 정확히 입력하세요"
        elif not (username and pw and repw and email and hp and name):
            msg['err'] = '모든 값을 입력하세요'
        else :
            m = Member(
                    username=username,
                    pw=make_password(pw),
                    hp=hp,
                    email=email,
                    name=name
                    )
            m.save()
        return render(request, 'member/insert.html', msg)

django2/mysecond/member/templates/member/detail.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<script>
    function delchk(){
        r=confirm('정말로 삭제?')
        if (r==true){
            u = '/member/'+{{m.id}}+'/delete'
            alert(u)
            location.href=u
        }
    }
</script>
<h2>member/detail</h2>
<p/>
<table class="table">
    <tr>
        <td>회원번호 : </td>
        <td>{{ m.id }}</td>
    </tr>
    <tr>
        <td>username : </td>
        <td>{{ m.username }}</td>
    </tr>
    <tr>
        <td>hp : </td>
        <td>{{ m.hp }}</td>
    </tr>
    <tr>
        <td>email : </td>
        <td>{{ m.email}}</td>
    </tr>
    <tr>
        <td>name : </td>
        <td>{{ m.name }}</td>
    </tr>
</table>
<p/>
<a href="{% url 'member:list2' %}" class="btn btn-success" role="button">목록보기</a>
<a href="javascript:delchk()" class="btn btn-danger" role="button">삭제</a>
<a href="{% url 'member:update' m.id%}" class="btn btn-warning" role="button">수정</a>
{% endblock %}

django2/mysecond/member/templates/member/index.html
{% extends 'base.html' %}
{% block title %}회원게시판{% endblock %}
{% block content %}
{% for n in names %}
    <div>{{n}}</div>
{% endfor %}
========================================
{% for c in colors %}
    <div>{{c|upper}}</div>
    <div>글자수 : {{c|length}}</div>
{% endfor %}
========================================
{% for no in number %}
    <div>{{no}} - {{no|add:'3'}} - {{no|add:no}}</div>
{% endfor %}
{% endblock %}

django2/mysecond/member/templates/member/insert.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<h2>회원가입</h2>
<div>{{ err }}</div>
<form method="post" action=".">
    {% csrf_token %}
    <div>
        사용자 id : <input type="text" name="username" maxlength="50">
    </div>
    <div>
        암  호 : <input type="password" name="pw" maxlength="50">
    </div>
    <div>
        암호확인 : <input type="password" name="repw">
    </div>
    <div>
        핸 드 폰 : <input type="text" name="hp" maxlength="50">
    </div>
    <div>
        Email : <input type="text" name="email" maxlength="50">
    </div>
    <div>
        사용자명 : <input type="text" name="name" maxlength="50">
    </div><br>
    <button type="submit" class="btn btn-success">완료</button>
    <button type="reset" class="btn btn-danger">취소</button>
</form>
<br>
<a href="{% url 'member:list2' %}" class="btn btn-success" role="button">목록보기</a>
{% endblock %}

django2/mysecond/member/templates/member/list.html
{% extends 'base.html' %}
{% block title %}회원리스트{% endblock %}
{% block content %}
<h2>member/list</h2>
<ul class="container">
{% for m in ms %}
    <li class="list-group-item"><a href="{% url 'member:detail' m.id %}">{{ m.username }} - {{ m.email }}</a></li>
{% endfor %}
</ul>
<p/>
<a href="{% url 'member:insert2' %}" class="btn btn-success" role="button">회원등록</a>
{% endblock %}

django2/mysecond/member/templates/member/update.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<h2>member/update</h2>
<table class="table">
<form action="." method="post">
    {%csrf_token%}
    <tr>
        <td>회원번호(수정불가) : </td>
        <td><input type="text" value="{{m.id}}" name="id" readonly="readonly"></td>
    </tr>
    <tr>
        <td>username : </td>
        <td><input type="text" value="{{ m.username }}" name="username"></td>
    </tr>
    <tr>
        <td>hp : </td>
        <td><input type="text" value="{{ m.hp }}" name="hp"></td>
    </tr>
    <tr>
        <td>email : </td>
        <td><input type="text" value="{{ m.email}}" name="email"></td>
    </tr>
    <tr>
        <td>name : </td>
        <td><input type="text" value="{{ m.name }}" name="name"></td>
    </tr>
    <tr>
    <td colspan="2"><button type="submit" class="btn btn-success">수정완료</button>
    <button type="reset" class="btn btn-danger">취소</button></td>
    </tr>
    <input type="hidden" value="{{ m.pw }}" name="pw">
    <input type="hidden" value="{{ m.regdate }}" name="regdate">
</form>
</table>
{% endblock %}